version: "3.8"
name: loola

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9005:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: loola
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local