version: "3.8"
name: fixlane

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    healthcheck:
      test: ["CMD", "php", "artisan", "config:show", "app.key"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 5s
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fixlane_shared

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9005:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fixlane_shared

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: fixlane
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - fixlane_shared

networks:
  fixlane_shared:
    name: fixlane_shared  

volumes:
  db:
    driver: local